theme = "material_deep_ocean"

[editor]
line-number = "relative"

[editor.statusline]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
center = ["version-control"]

[editor.cursor-shape]
normal = "block"
insert= "bar"
select = "underline"


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "select_line_above"
D = "kill_to_line_end"
ret = "goto_word"
"C-r" = ":reload-all"
"C-ret" = "insert_newline"
"C-j" = "insert_newline"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

"C-p" = ":pipe-to ~/.config/helix/send-to-ipython.sh"

# Launch lazygit inside helix!
C-x = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all"]
C-y = [":sh tmux split-window 'YAZI_CONFIG_HOME=~/.config/yazi/sidebar yazi'"]

[keys.normal.space]
# Open file picker relative to current file
"-" = "file_picker_in_current_buffer_directory"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

"C-p" = ":pipe-to ~/.config/helix/send-to-ipython.sh"


[keys.insert]
# Added some Emacs movement to the INSERT mode (instead of cursors, makes sense)
"C-p" = "move_line_up"
"C-n" = "move_line_down"
"C-f" = "move_char_right"
"C-g" = "move_char_left"
"C-a" = "goto_line_start"
"C-e" = "goto_line_end_newline"
"A-f" = "move_next_word_start"
"A-b" = "move_prev_word_start"

# TESTING: exit insert mode by pressing j twice
j = { j = "normal_mode" }
